---

- name: install Python
  command: sudo amazon-linux-extras install python3.8 -y

- name: Install pip3
  become: yes
  yum:
    name: python3-pip
    state: present

- name: upgrade all packages
  become: yes
  yum: 
    name: '*'
    state: latest
    
 

- name: Install required Python packages
  become: yes
  pip:
    executable: /usr/bin/pip3.8
    name:
      - asgiref==3.5.0
      - backports.zoneinfo
      - dj-database-url==0.5.0
      - Django==4.0.3
      - gunicorn==20.1.0
      - psycopg2-binary==2.9.3
      - sqlparse==0.4.2
      - whitenoise==6.0.0
    state: present
