




---
- name: run app
  become: yes
  command: /usr/local/bin/gunicorn wsgi -b 127.0.0.1:8000 --pid /tmp/gunicorn.pid --daemon
  args:
    chdir: /home/ec2-user/sample-django-main
  environment:
     DEBUG: "{{ DEBUG }}"
     DJANGO_ALLOWED_HOSTS: "{{ DJANGO_ALLOWED_HOSTS }}"
     DEVELOPMENT_MODE: "{{ DEVELOPMENT_MODE }}"
     DATABASE_URL: "{{ DATABASE_URL }}"
  depends_on: run db migration